# Puerto de Spring Boot
server.port = 8080

#Configuración de Base de Datos H2
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:notasdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.datbase-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update